### ISSUE TITLE
Accept null objects in deep path

### ISSUE THREAD

**Issue by Rhobal** [smart-table/smart-table-json-pointer#2]
I load objects from a backend where included objects might be null. pointer() currently throws exceptions when trying to dereference the null object. I think null should handled gracefully, same as undefined

**Comment by lorenzofox3** [comment]
Hey, 

I am not sure about that one: null and undefined have different semantic. You could for example have someone making a search (thinking in smart table context) for null value whereas undefined is the absence of value. 

I think this should be an option where the default value would be to throw. What are you thoughts ? 
And sorry I had forgotten about your PR  !

**Comment by Rhobal** [comment]
I think that smart table should be resilient to badly formed or missing data on input and not throw; it's primarily a convenience tool for the view.
With the PR, one could still search for `null`; it's just that both `{foo: null}` and `{foo: {bar: null}}` would both both return `null` for the `foo.bar` pointer.

**Comment by lorenzofox3** [comment]
you are right gonna merge your pr
